ALTER TABLE emp ADD(reports_to NUMBER(3) CONSTRAINT FK_REPORTS_TO_EMPCODE REFERENCES emp(empcode));

ALTER TABLE skill ADD CONSTRAINT ID_STARTS_WITH_S CHECK(skillid LIKE 'S%');

ALTER TABLE emp_skill ADD CONSTRAINT PK_EMPNO_SKILLID PRIMARY KEY(empno, skillid);

ALTER TABLE prj_details ADD CONSTRAINT UNQ_PRJ_NAME UNIQUE(prj_name);

ALTER TABLE client ADD(email VARCHAR(20) CONSTRAINT VALID_EMAIL CHECK(email LIKE '%@.___'));

ALTER TABLE emp ADD CONSTRAINT UNQ_PHONE UNIQUE(phone);

ALTER TABLE emp ADD CONSTRAINT UNQ_EMAIL UNIQUE(email);

ALTER TABLE medical_policy DROP PRIMARY KEY;
ALTER TABLE medical_policy ADD CONSTRAINT PK_MED PRIMARY KEY(empno, policyno, policydate);

ALTER TABLE medical_policy DROP CONSTRAINT PREMIUM_POSITIVE;
ALTER TABLE medical_policy ADD CONSTRAINT PREM_MORE_THAN_THOUSAND CHECK(premium > 1000);